from alpha_vantage.techindicators import TechIndicators
import pandas as pd
from time import time
from time import sleep

cnt = 0
t0 = time()

def call_check():
    global cnt
    global t0
    
    cnt += 1
    t = time() - t0
    if t <= 60 and cnt >= 5:
        sleep(60)
        cnt = 0
        t0 = time()
    elif t > 60:
        cnt = 0
    

def save_ti(ticker, interval='daily'):
    ti = TechIndicators(key='WS8K5VM8FZL52BTH', output_format='pandas')
        
    ti.get_sma(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_sma.csv')
    call_check()
    ti.get_ema(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ema.csv')
    call_check()
    ti.get_wma(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_wma.csv')
    call_check()
    ti.get_dema(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_dema.csv')
    call_check()
    ti.get_tema(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_tema.csv')
    call_check()
    ti.get_trima(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_trima.csv')
    call_check()
    ti.get_kama(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_kama.csv')
    call_check()
    ti.get_mama(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_mama.csv')
    call_check()
    ti.get_t3(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_t3.csv')
    call_check()
    ti.get_macd(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_macd.csv')
    call_check()
    ti.get_macdext(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_macdext.csv')
    call_check()
    ti.get_stoch(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_stoch.csv')
    call_check()
    ti.get_stochf(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_stochf.csv')
    call_check()
    ti.get_rsi(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_rsi.csv')
    call_check()
    ti.get_stochrsi(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_stochris.csv')
    call_check()
    ti.get_willr(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_willr.csv')
    call_check()
    ti.get_adx(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_adx.csv')
    call_check()
    ti.get_adxr(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_adxr.csv')
    call_check()
    ti.get_apo(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_apo.csv')
    call_check()
    ti.get_ppo(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ppo.csv')
    call_check()
    ti.get_mom(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_mom.csv')
    call_check()
    ti.get_bop(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_bop.csv')
    call_check()
    ti.get_cci(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_cci.csv')
    call_check()
    ti.get_cmo(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_cmo.csv')
    call_check()
    ti.get_roc(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_roc.csv')
    call_check()
    ti.get_rocr(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_rocr.csv')
    call_check()
    ti.get_aroon(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_aroon.csv')
    call_check()
    ti.get_aroonosc(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_aroonosc.csv')
    call_check()
    ti.get_mfi(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_mfi.csv')
    call_check()
    ti.get_trix(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_trix.csv')
    call_check()
    ti.get_ultosc(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ultosc.csv')
    call_check()
    ti.get_dx(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_dx.csv')
    call_check()
    ti.get_minus_di(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_minus_di.csv')
    call_check()
    ti.get_plus_di(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_plus_di.csv')
    call_check()
    ti.get_minus_dm(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_minus_dm.csv')
    call_check()
    ti.get_plus_dm(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_plus_dm.csv')
    call_check()
    ti.get_bbands(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_bbands.csv')
    call_check()
    ti.get_midpoint(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_midpoint.csv')
    call_check()
    ti.get_midprice(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_midprice.csv')
    call_check()
    ti.get_sar(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_sar.csv')
    call_check()
    ti.get_trange(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_trange.csv')
    call_check()
    ti.get_atr(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_atr.csv')
    call_check()
    ti.get_natr(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_natr.csv')
    call_check()
    ti.get_ad(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ad.csv')
    call_check()
    ti.get_adosc(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_adosc.csv')
    call_check()
    ti.get_obv(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_obv.csv')
    call_check()
    ti.get_ht_trendline(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ht_trendline.csv')
    call_check()
    ti.get_ht_sine(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ht_sine.csv')
    call_check()
    ti.get_ht_trendmode(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ht_trendmode.csv')
    call_check()
    ti.get_ht_dcperiod(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_dcperiod.csv')
    call_check()
    ti.get_ht_dcphase(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_dcphase.csv')
    call_check()
    ti.get_ht_phasor(ticker, interval)[0].to_csv(f'./Stock Data/TI/{ticker}_{interval}_ht_phasor.csv')